// Auto-generated by scripts/fetchSlots.mjs — do not edit manually
// Last updated: 2026-05-29T23:22:26.526Z

export interface SlotGame {
  id: number
  name: string
  slug: string
  provider: "Pragmatic Play" | "Hacksaw Gaming" | "Nolimit City"
  providerSlug: string
  rtp: number
  maxWin: string
  volatility: 1 | 2 | 3
  iframeUrl: string
  thumb: string | null
  releaseDate: string | null
  featured?: boolean
  localBadge?: string
}

export const slots: SlotGame[] = [
  {
    "id": 90000,
    "name": "Gates of Gatot Kaca",
    "slug": "gates-of-gatot-kaca",
    "provider": "Pragmatic Play",
    "providerSlug": "pragmatic-play",
    "rtp": 96.5,
    "maxWin": "x5,000",
    "volatility": 3,
    "iframeUrl": "https://gates-of-gatot-kaca.slot.day/?playfree=1",
    "thumb": null,
    "releaseDate": null,
    "featured": true,
    "localBadge": "🇮🇩 UNGGULAN"
  },
  {
    "id": 90001,
    "name": "Gates of Olympus",
    "slug": "gates-of-olympus",
    "provider": "Pragmatic Play",
    "providerSlug": "pragmatic-play",
    "rtp": 96.5,
    "maxWin": "x15,000",
    "volatility": 3,
    "iframeUrl": "https://slot.day/pragmatic-play/gates-of-olympus/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90002,
    "name": "Sweet Bonanza",
    "slug": "sweet-bonanza",
    "provider": "Pragmatic Play",
    "providerSlug": "pragmatic-play",
    "rtp": 96.51,
    "maxWin": "x21,100",
    "volatility": 3,
    "iframeUrl": "https://slot.day/pragmatic-play/sweet-bonanza/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90003,
    "name": "Starlight Princess",
    "slug": "starlight-princess",
    "provider": "Pragmatic Play",
    "providerSlug": "pragmatic-play",
    "rtp": 96.5,
    "maxWin": "x5,000",
    "volatility": 3,
    "iframeUrl": "https://slot.day/pragmatic-play/starlight-princess/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90004,
    "name": "Big Bass Bonanza",
    "slug": "big-bass-bonanza",
    "provider": "Pragmatic Play",
    "providerSlug": "pragmatic-play",
    "rtp": 96.71,
    "maxWin": "x2,100",
    "volatility": 2,
    "iframeUrl": "https://slot.day/pragmatic-play/big-bass-bonanza/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90005,
    "name": "The Dog House",
    "slug": "the-dog-house",
    "provider": "Pragmatic Play",
    "providerSlug": "pragmatic-play",
    "rtp": 96.51,
    "maxWin": "x6,750",
    "volatility": 3,
    "iframeUrl": "https://slot.day/pragmatic-play/the-dog-house/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90006,
    "name": "Sugar Rush",
    "slug": "sugar-rush",
    "provider": "Pragmatic Play",
    "providerSlug": "pragmatic-play",
    "rtp": 96.5,
    "maxWin": "x5,000",
    "volatility": 3,
    "iframeUrl": "https://slot.day/pragmatic-play/sugar-rush/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90007,
    "name": "Wanted Dead or a Wild",
    "slug": "wanted-dead-or-a-wild",
    "provider": "Hacksaw Gaming",
    "providerSlug": "hacksaw-gaming",
    "rtp": 96.38,
    "maxWin": "x12,500",
    "volatility": 3,
    "iframeUrl": "https://slot.day/hacksaw-gaming/wanted-dead-or-a-wild/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90008,
    "name": "Chaos Crew",
    "slug": "chaos-crew",
    "provider": "Hacksaw Gaming",
    "providerSlug": "hacksaw-gaming",
    "rtp": 96.3,
    "maxWin": "x10,000",
    "volatility": 3,
    "iframeUrl": "https://slot.day/hacksaw-gaming/chaos-crew/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90009,
    "name": "Book of Time",
    "slug": "book-of-time",
    "provider": "Hacksaw Gaming",
    "providerSlug": "hacksaw-gaming",
    "rtp": 96.13,
    "maxWin": "x10,000",
    "volatility": 3,
    "iframeUrl": "https://slot.day/hacksaw-gaming/book-of-time/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90010,
    "name": "Eye of Medusa",
    "slug": "eye-of-medusa",
    "provider": "Hacksaw Gaming",
    "providerSlug": "hacksaw-gaming",
    "rtp": 96.2,
    "maxWin": "x15,000",
    "volatility": 3,
    "iframeUrl": "https://slot.day/hacksaw-gaming/eye-of-medusa/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90011,
    "name": "RIP City",
    "slug": "rip-city",
    "provider": "Hacksaw Gaming",
    "providerSlug": "hacksaw-gaming",
    "rtp": 96.3,
    "maxWin": "x12,500",
    "volatility": 3,
    "iframeUrl": "https://slot.day/hacksaw-gaming/rip-city/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90012,
    "name": "Le Bandit",
    "slug": "le-bandit",
    "provider": "Hacksaw Gaming",
    "providerSlug": "hacksaw-gaming",
    "rtp": 96.3,
    "maxWin": "x10,000",
    "volatility": 3,
    "iframeUrl": "https://slot.day/hacksaw-gaming/le-bandit/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90013,
    "name": "Cash Quest",
    "slug": "cash-quest",
    "provider": "Hacksaw Gaming",
    "providerSlug": "hacksaw-gaming",
    "rtp": 94.36,
    "maxWin": "x7,500",
    "volatility": 2,
    "iframeUrl": "https://slot.day/hacksaw-gaming/cash-quest/?playfree=1",
    "thumb": null,
    "releaseDate": null
  },
  {
    "id": 90014,
    "name": "Beat the Bobbies",
    "slug": "beat-the-bobbies",
    "provider": "Hacksaw Gaming",
    "providerSlug": "hacksaw-gaming",
    "rtp": 95,
    "maxWin": "x10,000",
    "volatility": 3,
    "iframeUrl": "https://slot.day/hacksaw-gaming/beat-the-bobbies/?playfree=1",
    "thumb": null,
    "releaseDate": null
  }
]

export const HOME_FEATURED_SLOT_SLUGS = [
  "gates-of-gatot-kaca",
  "gates-of-olympus",
  "wanted-dead-or-a-wild",
  "sweet-bonanza",
] as const

export function getSlotById(idOrSlug: string): SlotGame | undefined {
  return slots.find(
    (slot) => slot.slug === idOrSlug || String(slot.id) === idOrSlug,
  )
}

export function getHomeFeaturedSlots(): SlotGame[] {
  return HOME_FEATURED_SLOT_SLUGS.map((slug) =>
    slots.find((slot) => slot.slug === slug),
  ).filter((slot): slot is SlotGame => slot !== undefined)
}
